# theme = 'github_dark_colorblind'
# theme = 'tokyonight'
theme = 'nightfox'

[editor]
line-number = "relative"
mouse = true
auto-save = true
auto-format = true
true-color = true
bufferline = "multiple"
auto-pairs = true
cursorline = false
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
color-modes = true
idle-timeout = 100

[editor.lsp]
display-messages = false
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control"]
center = ['file-name','file-modification-indicator']
right = ['diagnostics','selections','position','file-encoding','file-line-ending','file-type']
separator = "|"
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
tabpad = "·" # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "┆" # Some characters that work well: "▏", "┆", "┊", "⸽", "╎"
skip-levels = 1

[keys.normal]
C-s = ':write!'
C-q = [":quit"]
C-Q = [":quit!"]
H = ":buffer-previous"
L =":buffer-next"
esc = ["collapse_selection", "keep_primary_selection"]
"C-/" = ["toggle_comments"]
X = ["extend_line_above"]

[keys.insert]
j = {k = ["normal_mode", 'collapse_selection','keep_primary_selection']}
C-s = ["normal_mode", ":write!"]
"C-/" = ["toggle_comments"]

[keys.normal.space]
x = ":sh biome stop"
c = ":buffer-close"
'/' = "toggle_comments"
space = "buffer_picker"
b = "no_op"

# [keys.normal.space.l]
# p = ":sh python $fp"

[keys.normal.space.q]
q = [":quit"]
w = ":wq"
x = ":quit!"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "⮐"
