# theme = 'github_dark_colorblind'
# theme = 'tokyonight'
theme = 'nightfox'

[editor]
line-number = "relative"
mouse = true
auto-save = true
auto-format = true
true-color = true
bufferline = "multiple"
auto-pairs = true
cursorline = false
gutters = ["diagnostics", "spacer","line-numbers","spacer","diff"]
color-modes = true
idle-timeout = 100

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]
center = ['file-name']
right = ['diagnostics','selections','position','file-encoding','file-line-ending','file-type']
separator = "|"
mode.insert = "INSERT"
mode.normal = "NORMAL"
mode.select = "SELECT"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"
# tabpad = "·" # Tabs will look like "→···" (depending on tab width)
tabpad = " " # Tabs will look like "→···" (depending on tab width)

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-s = ':write!'
H = ":buffer-previous"
L =":buffer-next"
esc = ["collapse_selection", "keep_primary_selection"]
"C-/" = ["toggle_comments"]

[keys.insert]
j = {k = "normal_mode"}
C-s = ["normal_mode", ":write!"]
"C-/" = ["toggle_comments"]

[keys.normal.space]
c = ":buffer-close"
'/' = "toggle_comments"
space = "buffer_picker"

[keys.normal.space.q]
q = ":quit"
w = ":wq"
x = ":quit!"

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "⮐"
