
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [2,4,3]
sort_dir_first = true
show_symlink = true
linemode    = "size"
show_hidden = true
sort_by     = "natural"

[preview]
tab_size   = 2
max_width  = 600
max_height = 900
cache_dir = ""
ueberzug_scale = 1
ueberzug_offset = [0,0,0,0]

[opener]
edit = [
    { run = 'code "%*"', desc = "VS Code", orphan=true},
]
# open = [
#     {run = 'start "" "%1"', orphan=true, desc="Open" },
# ]
reveal = [
    {run = 'explorer /select, "%1"', orphan = true, desc="Reveal"}
]
extract = [
    {run = 'unar "%1"', desc="Extract here"}
]
archive = [
    {run = 'winrar "%1"', desc="Archive"}
]
play = [
    {run = 'vlc "%1"', orphan=true}
]

[open]
rules = [
    { name = "*/", use = [ "open", "edit", "reveal" ] },

    { mime = "text/*",  use = [ "edit", "reveal" ] },
    { mime = "image/*", use = [ "open", "reveal" ] },
    { mime = "video/*", use = [ "play", "reveal" ] },
    { mime = "audio/*", use = [ "play", "reveal" ] },
    { mime = "inode/x-empty", use = [ "edit", "reveal" ] },
    
    { mime = "application/json", use = [ "edit", "reveal" ] },
    { mime = "*/javascript",     use = [ "edit", "reveal" ] },
    
    { mime = "application/zip",             use = [ "extract", "reveal", "archive" ] },
    { mime = "application/gzip",            use = [ "extract", "reveal", "archive" ] },
    { mime = "application/x-tar",           use = [ "extract", "reveal", "archive" ] },
    { mime = "application/x-bzip",          use = [ "extract", "reveal", "archive" ] },
    { mime = "application/x-bzip2",         use = [ "extract", "reveal", "archive" ] },
    { mime = "application/x-7z-compressed", use = [ "extract", "reveal", "archive" ] },
    { mime = "application/x-rar",           use = [ "extract", "reveal", "archive" ] },
    
    { mime = "*", use = [ "open", "reveal" ] },
]

[plugin]
prepend_previewers = [
    { mime = "audio/*", run = "exifaudio" },
]
append_previewers = [
    { name = "*" , run = "binary" },
]
